---
- name: Converge
  hosts: servers
  tasks:
    - name: Configure NGINX
      ansible.builtin.include_role:
        name: nginxinc.nginx_config
      vars:
        nginx_config_debug_output: true

        nginx_config_upload_enable: true
        nginx_config_upload:
          - src: ./nginx.conf
            dest: /etc/nginx/nginx.conf
            backup: true
  become: true
